# This -*- perl -*- script writes the Makefile for Time::Duration
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
require 5.004;
use strict;
use ExtUtils::MakeMaker;

WriteMakefile(
    'NAME'	=> 'Time::Duration',
    'VERSION_FROM' => 'Duration.pm', # finds $VERSION
    'ABSTRACT_FROM' => 'Duration.pm',
    'dist'        => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
);

package MY;

sub libscan
{ # Determine things that should *not* be installed
    my($self, $path) = @_;
    return '' if $path =~ m/~/;
    $path;
}

__END__
